name = "l"
type = "webpack"

workers_dev = true
vars = {TOKEN="1067208185:AAG0CzzAh89k3GHsx_i19MjhDA2meW5BgDI",X='',CTX='',F='',B=""}
# kv_namespaces = [                                                                                                                                                                                            
#          { binding = "M", id = "f0794462b83749ad952efebfec73df9d" }                                                                                                                                          
# ]
[site]
bucket = "./public"
entry-point = "."
